### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by angrybrad**
Enjoy!

### CODE REVIEW

**Comment by dreamseeker** [comment]
Hi.

I translated Crowdin as follows:

```
::: tip
(My Translate Message)
:::
```

https://crowdin.com/translate/craft-docs/1218/en-ja

However, the line break in the custom container has been deleted in the commit data.

```
::: tip (My Translate Message) :::
```

https://github.com/craftcms/docs/pull/9/commits/f4493059738b32195cf7bff5c8184a41cd912a59#diff-d1f82c43177f97c245d9918456b39c60R9

Therefore, I think that it will be an unintended display on the front end.
Is there a way to solve this problem?

**Comment by angrybrad** [comment]
@dreamseeker yeah, I think that will mess things up on the front-end.  Let me research why it's happening on Crowdin.

**Comment by angrybrad** [comment]
I think it's a bug in the Github integration - I've contacted them about it.

**Comment by angrybrad** [comment]
> Thanks a lot for the provided details! Much appreciated!
> Our developers are working on issues related to MD files, they did a few fixes, so I believe this one will be fixed as well
> I'll create a task for developers and once we have any news on the matter - you will be first to know!
> Thanks for understanding!

I guess in the meantime, we'll go through and manually fix the PRs before merging.

**Comment by dreamseeker** [comment]
@angrybrad thanks for your support!

**Comment by angrybrad** [comment]
@dreamseeker got a response from them and looks like it's fixed! https://github.com/craftcms/docs/pull/17/commits/6accdc0fed17d7caea22fbf771e8253a4fd2d243

**Pull request closed without merging**
