### PR TITLE
Add Element Exporters

### PR DESCRIPTION
**Pull request by billythekid**
I've written a section on Exporters. I wasn't sure if it should go into System Components or More, so put it in More.

### CODE REVIEW

**Comment by mattstein** [comment]
This is excellent, thank you for taking the time to write and provide examples @billythekid! I hope you don’t mind I gave it a once-over with minor edits.

**Comment by billythekid** [comment]
Heh, that's awesome man, glad it was of some help for you, hopefully it will be to others too. No worries on the edits, fully expected it to be altered, surprised you accepted it at all in fact, lol.

Cheers

**Review by brandonkelly — APPROVED** [review]

**Comment by brandonkelly** [comment]
Thanks for getting this going, @billythekid! Will merge this in once 3.4.10 is released (which changes all generic XML node names to `<item>` instead of the exported element type).

**Comment by brandonkelly** [comment]
Page is live now! https://docs.craftcms.com/v3/extend/element-exporter-types.html#creating-custom-exporter-types

**Comment by billythekid** [comment]
Well done everyone. I quite liked developing on the vuepress system which was new to me. I'll need to look into it more thoroughly as things like that tabbed output for multiple formats CSV/XML/JSON is really nice but I simply didn't know they existed. 
Hopefully people will find this helpful now you've got it up to scratch!
Cheers!

**Comment by brandonkelly** [comment]
@billythekid Yeah that’s a custom Markdown extension we built for the docs :)

**Pull request merged**
