### PR TITLE
Update cp-section.md

### PR DESCRIPTION
**Pull request by Toastgeraet**
Fixed the documentation to something that actually works.

### CODE REVIEW

**Comment by khalwat** [comment]
This isn't the right way to solve the issue imo.

You can either:

*  Change the `hasCpSection` setting in your plugin's `composer.json` and do a `composer update` on your project
-or-
* Remove the `hasCpSection` key from your `composer.json`, do a `composer update` and set the property directly in your plugin's class as the documentation (correctly) describes

What's happening is because you have a `hasCpSection` setting in `extras` in your `composer.json`, this value is cached and copied into the `vendor/craftcms/plugins.php` file.

When your plugin's class is instantiated, the settings cached in the `vendor/craftcms/plugins.php` for it are passed into the plugin's constructor to set those properties. This is why the setting in `plugins.php` overrides what you've tried to set via the property as the docs describe.

So while this PR will technically work, I think it's side-stepping the issue.

**Comment by mattstein** [comment]
Thanks for the PR, @Toastgeraet! The problem here is that `hasCpSection` as defined in `composer.json` will override the class-defined value. While your solution works because of _when_ it’s called in `init()`, we’d still recommend either setting the value in `composer.json` **or** in your plugin’s class as @khalwat recommends—but not both.

**Comment by Toastgeraet** [comment]
@khalwat Well this issue is really caused by side effect imo. At the very least the documentation should mention, that this way to configure is superceded by the presence of the extra field in composer.json.

Anyway, thanks for letting me know, about the reason why the 'correct' docs instructiond, do not work.

**Comment by Toastgeraet** [comment]
And there have been many people having problems with this, when you search the craftcms discord channels...

**Comment by khalwat** [comment]
@Toastgeraet yep I 100% agree with you that the docs should mention the presence of the `craftcms/plugins.php` file, how it operates, etc. You are not the first person or the last person who has had this issue.

No question it should be documented imo.

**Pull request closed without merging**
